config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'tags/:tag', to: 'articles#index', as: :tag
  resources :articles
  root to: 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  attr_accessible :body, :title, :tag_list
  acts_as_taggable

  validates :title,
            :presence => true, on: :update

  validates :title,
            :presence => true, on: :create


  validates :body,
            :presence => true, on: :update

  validates :body,
            :presence => true, on: :create


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    if params[:tag]
    @articles = Article.tagged_with(params[:tag])
  else
    @articles = Article.all
  end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.tag_list.add(params[:tag_list], parse: true)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article.tag_list.add(params[:tag_list], parse: true)
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end


  
  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :created_at, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <h5>Title</h5>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <h5>Body</h5>
    <%= f.text_area :body %>
  </div>
  

   <div class="field">
  <h5><%= f.label :tag_list, "Tags (separated by commas)" %></h5>
  <%= f.text_field :tag_list, value:@article.tag_list.to_s %>
  </div>

  <br>

  <div class="field"><%=f.submit%></div>

 



<% end %>

app/views/articles/edit.html.erb
<div class="container">
<br>

<nav class="navbar navbar-light bg-faded">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
    <a class="navbar-brand" href="#">MyBlog</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', articles_path, class:'btn btn-info'%><span class="sr-only">(current)</span>
        <%= link_to 'About', page_path('about'), class:'btn btn-info'%>
      </li>

    </ul>
  </div>
</nav>

<div class="row">
  <div class="col-sm-8">
<br>
<h1 class="card-title">Editing Article</h1>
	<div class="card card-block">
  		
  		<p class="card-title"><%= render 'form' %></p>
  		<a href="#" class="card-link"><%= link_to 'Show', @article %></a>
  		<a href="#" class="card-link"><%= link_to 'Back', articles_path %></a>
	</div>

  </div>
</div>

</div>

app/views/articles/index.html.erb
<div class="container">
<br>

      <nav class="navbar navbar-light bg-faded">
        <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
          &#9776;
        </button>
        <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
          <a class="navbar-brand" href="#">MyBlog</a>
          <ul class="nav navbar-nav">
            <li class="nav-item active">
              <%= link_to 'Home', articles_path, class:'btn btn-info'%><span class="sr-only">(current)</span>
              <%= link_to 'New Article', new_article_path(@articles), class:'btn btn-info' %>
              <%= link_to 'About', page_path('about'), class:'btn btn-info'%>

            </li>

          </ul>
        </div>
      </nav>




<br>

      <h1>MyBlog</h1>
      <h5>My first Rails Application for CoderSchool</h5>

      <p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-8">



  <% @articles.each do |article| %>
    <div class="card">
      <div class="card-block">
        <h4 class="card-title"><%= article.title %></h4>
        <p class="card-text"><%= @markdown.render(article.body).html_safe %></p>
        <p align="right"><i>Created on <%=article.created_at.in_time_zone("Hanoi").to_s(:short)%> GMT+7</i></p> 
      </div>
      <div class="card-footer">
        <%= link_to 'Edit', edit_article_path(article), class:'btn btn-info' %>
        <%= link_to "Delete", article_path(article), method: :delete, class:'btn btn-info', data: { confirm: 'Are you sure you want to delete this item?'} %>
      </div>


      <div class="card-footer">
        <p>Tags: <%= raw article.tag_list.map { |t| link_to t, tag_path(t), class: 'btn btn-info-outline' }.join('  ')   %></p>
      </div>
      </div>
      <% end %>


  <p>
    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    See tag list
    </a>
  </p>
  <div class="collapse" id="collapseExample">
    <div class="card card-block">
      <% tag_cloud Article.tag_counts, %w{s m l} do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: 'btn btn-info-outline' %>
      <% end %>
    </div>
  </div>


 

  </div>
</div>
</div>

app/views/articles/new.html.erb
<div class="container">

<br>
<nav class="navbar navbar-light bg-faded">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
    <a class="navbar-brand" href="#">MyBlog</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', articles_path, class:'btn btn-info'%><span class="sr-only">(current)</span>
        <%= link_to 'About', page_path('about'), class:'btn btn-info'%>
      </li>

    </ul>
  </div>
</nav>

<div class="row">
  <div class="col-sm-8">
  	<br>
  	<h1>New Article</h1>
	<div class="card card-block">
  	<p class="card-text"><%= render 'form' %></p>
  	<a href="#" class="card-link"><%= link_to 'Back', articles_path %></a>
	</div>

  </div>
</div>

</div>

app/views/articles/show.html.erb
<div class="container">
<br>
<nav class="navbar navbar-light bg-faded">
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
    &#9776;
  </button>
  <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
    <a class="navbar-brand" href="#">MyBlog</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', articles_path, class:'btn btn-info'%><span class="sr-only">(current)</span>
        <%= link_to 'About', page_path('about'), class:'btn btn-info'%>
      </li>

    </ul>
  </div>
</nav>

<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-8">


	<div class="card card-block">
  		<h5 class="card-title">Title: <%= @article.title %></h5>
  		<p class="card-title"><%= @markdown.render(@article.body).html_safe %></p>
  		<a href="#" class="card-link"><%= link_to 'Edit', edit_article_path(@article) %> |
			<%= link_to 'Back', articles_path %></a>
	</div>


  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<div class="container">
<br>

      <nav class="navbar navbar-light bg-faded">
        <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
          &#9776;
        </button>
        <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
          <a class="navbar-brand" href="#">MyBlog</a>
          <ul class="nav navbar-nav">
            <li class="nav-item active">
              <%= link_to 'Home', articles_path, class:'btn btn-info'%><span class="sr-only">(current)</span>
              <%= link_to 'New Article', new_article_path(@articles), class:'btn btn-info' %>
              <%= link_to 'About', page_path('about'), class:'btn btn-info'%>

            </li>

          </ul>
        </div>
      </nav>




<br>

      <h1 style="color: #5e9ca0; text-align: left;">MyBlog - <span style="color: #2b2301;">About the author</span></h1>
<h2 style="color: #2e6c80; text-align: left;">Something about me:</h2>
<p style="text-align: left;">Hello, my name is Nhiem Ngo. I just graduated from High School for the Gifted in HCMC, and am currently taking a gap year before applying to US colleges.</p>
<p style="text-align: left;">Coding is one of my biggest hobbies and passions. I hope to be selected for CoderSchool's Ruby class so that I can take my Ruby&nbsp;skills to a new level.</p>
<h2 style="color: #2e6c80; text-align: left;">Here is a picture of me:</h2>
<p style="text-align: left;"><img src="http://i.imgur.com/01dIILe.jpg" alt="" width="480" height="480" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>

<div class="row">
  <div class="col-sm-8">




 

  </div>
</div>
</div>